#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor Virtual1 -d I II III IV V

bspc monitor Virtual2 -d VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Activa el portapeles bi direccional
vmware-user-suid-wrapper &

# Aciva el manager de backgrounds
feh --bg-fill /home/kur/Documents/Wallpapers/girlAloneInFrontOfAShrinePixelArt.png &

# Activa la polybar
~/.config/polybar/./launch.sh &

# Activa el picom
picom &

# Quita el borde que marca la ventana activa
bspc config border_width 0 &

# Arreglar el problema de que Burpsuite se mostrase el interfaz mal
wmname LG3D &
